version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: bar_system_postgres
    restart: always
    environment:
      POSTGRES_USER: baruser
      POSTGRES_PASSWORD: barpass
      POSTGRES_DB: bar_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
